---
title: "Shedd *Acropora cervicornis* transplant experiment"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, cache = FALSE, fig.width = 10)
library(lme4)
library(lsmeans)
library(multcomp)
library(tidyverse)
```

```{r}
# Import coral metadata
md <- read_csv("coral_metadata.csv") %>%
  mutate(source_location = factor(source_location, levels = c("BIM", "NAS", "CEI", "CAT", "EXU")))
```


```{r, include = FALSE}
# Import initial measurement data (2019-10-17)
init <- readxl::read_xlsx("data/tle/2019-10-17_ALL.xlsx") %>%
  janitor::clean_names() %>%
  select(1:6) %>%
  mutate(date = as.Date(date),
         tree = factor(tree),
         coral_id = factor(coral_id),
         frag_id = factor(frag_id))
```


```{r, include = FALSE}
# Create function to import data from standardized TLE datasheet
import_from_tle_datasheet <- function(xlsx) {
  # Read full datasheet
  ds <- readxl::read_xlsx(xlsx)
  # Read in header info for each tree (first 4 lines)
  tree_info <- readxl::read_xlsx(xlsx, n_max = 4, col_names = F) %>%
    select(seq(2, ncol(ds), 6)) %>%
    t() %>%
    magrittr::set_colnames(c("person", "date", "nursery", "tree")) %>%
    as_tibble() %>%
    mutate(date = janitor::excel_numeric_to_date(as.numeric(date)),
           tree = factor(tree))
  # Read in data sheet for all trees in datasheet
  ds <- readxl::read_xlsx(xlsx, skip = 4)
  # Split data sheet into a single data frame for each measured tree
  tree_data <- lapply(seq(1, ncol(ds), 6), function(x) ds[, x:(x + 5)])
  # Rearrange each tree's data frame into single set of columns
  tree_data <- map(tree_data, ~ rbind(as.matrix(.[, 1:3]), as.matrix(.[, 4:6]))) %>%
    map(~ magrittr::set_colnames(., c("coral_id", "frag_id", "tle"))) %>%
    map(~ as.data.frame(.))
  # Unnest into long form data frame
  dsf <- tree_info %>%
    mutate(data = tree_data) %>%
    unnest() %>%
    fill(coral_id)
  return(dsf)
}
```


```{r, include = FALSE}
# Import from all datasheets and join with initial data
# List data files (exluding initial data from all nurseries, imported above)
all_tle_datasheets <- list.files(path = "data/tle", full.names = TRUE) %>% 
  setdiff(c("data/tle/2019-10-17_ALL.xlsx", "data/tle/Breakage_report.xlsx"))

# Import data from all datasheets
tle <- map_dfr(all_tle_datasheets, import_from_tle_datasheet)

# Join with initial data and tidy
tle <- bind_rows(init, tle) %>%
  mutate(tle = str_split(tle, pattern = ","),
         tle_total = map_dbl(tle, ~ sum(as.numeric(.))),
         nursery = factor(nursery, levels = c("BIM", "NAS", "CEI", "CAT", "EXU")),
         days = as.numeric(date - as.Date("2019-10-12"))) %>%
  filter(coral_id != "(empty)")

# Import breakage report
breakage <- readxl::read_xlsx("data/tle/Breakage_report.xlsx", col_types = c("text")) %>%
  mutate(date = as.Date(as.character(date), format = "%Y%m%d"))

tle <- left_join(tle, breakage)

tle <- tle %>%
  group_by(tree, coral_id, frag_id) %>%             # group by fragment
  mutate(nbreak = cumsum(!is.na(breakage))) %>%     # get number of times each frag has broken
  ungroup() %>%
  mutate(frag_id = case_when(
    nbreak > 0 ~ paste(frag_id, nbreak, sep = "_"), # make new frag_id for frag after each breakage
    TRUE ~ frag_id)) %>%
  mutate(nursery = factor(nursery, levels = c("BIM", "NAS", "CEI", "CAT", "EXU")))

#tle %>% filter(tree == 147) %>% arrange(tree, coral_id, frag_id) %>% print(n = nrow(.))
```


# Average TLE for each genotype at each nursery
```{r, fig.height=8, fig.width=10}
tle %>%
  group_by(nursery, coral_id, date) %>%
  summarise(mean_tle = mean(tle_total, na.rm = T)) %>%
  ggplot(aes(x = date, y = mean_tle, group = coral_id, color = coral_id)) +
  geom_point() +
  geom_line() +
  facet_wrap(~ nursery) +
  scale_x_date(date_breaks = "months", date_labels = "%b '%y") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```


```{r, eval = FALSE}
# Average percent change for each genotype at each nursery
tle %>%
  group_by(nursery, tree, coral_id, frag_id) %>%
  mutate(pct_growth = tle_total / first(tle_total)) %>%
  group_by(nursery, coral_id, date) %>%
  summarise(mean_pct_growth = mean(pct_growth, na.rm = T)) %>%
  ggplot(aes(x = date, y = mean_pct_growth, group = coral_id, color = coral_id)) +
  geom_point() +
  geom_line() +
  facet_wrap(~ nursery)
```


```{r, eval = FALSE}
# TLE for all fragments
plots <- tle %>%
  group_by(nursery, tree) %>%
  nest() %>%
  mutate(plot = pmap(list(d = data, n = as.character(nursery), t = tree), function(d, n, t) {
    ggplot(d, aes(x = date, y = tle_total, group = frag_id, color = frag_id)) +
      facet_wrap(~ coral_id, scales = "free", nrow = 2) +
      geom_line() + geom_point() +
      labs(title = paste(n, "Tree", t), x = "", y = "Total Linear Extension (cm)") +
      theme(axis.text.x = element_text(angle = 45, hjust = 1))
    }))

plots %>% pull(plot)
```

# Specific growth rates of each genotype
```{r}
# Fit exponential model (log transform tle) - specific growth rate

# Fixed effects days, nursery, and coral_id, random intercepts and slopes for each fragment
mod <- lmer(log(tle_total) ~ days * coral_id + (days|nursery:tree:coral_id:frag_id), data = tle)

# Calculate slope (specific growth rate) for each coral_id at each nursery
emm_options(pbkrtest.limit = 3147)
lsm <- lstrends(mod, specs = "coral_id", var = "days")
# Summarize results in data frame
grates <- summary(lsm) %>%
  arrange(-days.trend) %>%
  full_join(rename(md, coral_id = source_coral_id)) %>%
  mutate(coral_id = factor(coral_id, levels = coral_id[rev(order(days.trend))]))


# Plot growth rates of each coral genotype
ggplot(grates, aes(x = coral_id, y = days.trend, color = source_location)) +
  geom_point() +
  geom_errorbar(aes(ymin = lower.CL, ymax = upper.CL), width = 0.5) +
  labs(x = "", y = "Specific growth rate (d^-1)")
```

# Specific growth rates of each genotype at each nursery
```{r, eval = T}
# Fit exponential model (log transform tle) - specific growth rate

# Fixed effects days, nursery, and coral_id, random intercepts and slopes for each fragment
mod <- lmer(log(tle_total) ~ days * nursery * coral_id + (days|tree:coral_id:frag_id), data = tle)

pred <- tidyr::expand(
  tle, nesting(nursery, coral_id, tree, frag_id), 
  days = seq(min(days), max(days), 2)
  ) %>% mutate(date = as.Date("2019-10-12") + days)

pred <- pred %>%
  mutate(log_tle_total = predict(mod, newdata = pred, allow.new.levels = TRUE),
         tle_total = exp(log_tle_total))

pp <- pred %>%
  group_by(nursery, tree) %>%
  nest(.key = "pred")


# Plot with fitted values
plots <- tle %>%
  group_by(nursery, tree) %>%
  nest() %>%
  full_join(pp) %>%
  mutate(plot = pmap(list(d = data, p = pred, n = as.character(nursery), t = tree), function(d, p, n, t) {
    ggplot(d, aes(x = date, y = tle_total, group = frag_id, color = frag_id, shape = frag_id)) +
      facet_wrap(~ coral_id, scales = "free", nrow = 2) +
      geom_line(lwd = 0.2) +
      #geom_line(data = p, lwd = 0.3) + 
      geom_point(alpha = 0.6) +
      labs(title = paste(n, "Tree", t), x = "", y = "Total Linear Extension (cm)") +
      scale_x_date(date_breaks = "months", date_labels = "%b '%y") +
      theme(axis.text.x = element_text(angle = 45, hjust = 1))
    }))

#plots %>% pull(plot)
```

```{r, fig.width = 10, fig.height = 10, eval = T}
# Calculate slope (specific growth rate) for each coral_id at each nursery
lsm <- lstrends(mod, specs = c("nursery", "coral_id"), var = "days")
# Summarize results in data frame
grates <- summary(lsm)
# Add home location to results
grates <- left_join(grates, select(md, coral_id = source_coral_id, home = source_location))
grates <- mutate(grates, at_home = as.character(nursery) == as.character(home))

# Test for differences among nurseries for each genotype
cldres2 <- CLD(lsm, by = "coral_id", alpha = 0.05, Letters = letters, adjust = "tukey")
posthocs <- data.frame(cldres2)
posthocs <- left_join(posthocs, dplyr::select(md, coral_id = source_coral_id, home = source_location)) %>%
  mutate(group = str_trim(.group))



# Plot growth rates of each coral at each nursery with standard error
ggplot(grates, aes(x = nursery, y = days.trend, color = at_home)) +
  facet_wrap(~ home + coral_id) +
  geom_point() +
  geom_errorbar(aes(ymin = lower.CL, ymax = upper.CL), width = 0.5) +
  geom_text(data = posthocs, aes(x = nursery, y = upper.CL + 0.001, label = group), size = 2.5, inherit.aes = FALSE) +
  labs(x = "", y = "Specific growth rate (d^-1)")
```

```{r}
#how much have corals increased over 295 days?
  
nasmu <- data.frame(cldres2) %>%
  filter(nursery == "NAS") %>%
  summarise(meanmu = mean(days.trend))
1*(1+nasmu)^295

ceimu <- data.frame(cldres2) %>%
  filter(nursery == "CEI") %>%
  summarise(meanmu = mean(days.trend))
1*(1+ceimu)^295

# how big is avg fragment if they started out as ~5cm
5*(1+ceimu)^295
```

# Plots for each fragment
```{r plots}
plots %>% pull(plot)

```

```{r, eval = F}
# Fit linear model - centimeters per day

# Fixed effects days, nursery, and coral_id, random intercepts and slopes for each fragment
mod <- lmer(tle_total ~ days * nursery * coral_id + (days|tree:coral_id:frag_id), data = newtle)

# Calculate slope (growth rate) for each coral_id at each nursery
lsm <- lstrends(mod, specs = c("nursery", "coral_id"), var = "days")
# Summarize results in data frame
grates <- summary(lsm)

# Plot growth rates of each coral at each nursery with standard error
ggplot(grates, aes(x = nursery, y = days.trend)) +
  facet_wrap(~ coral_id) +
  geom_point() +
  geom_errorbar(aes(ymin = lower.CL, ymax = upper.CL))
```


